### ISSUE TITLE
display blocks to the next epoch in status page

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/watchdog#27]
I'd like to see the number of blocks to the next epoch in both the watchdog page and the status page at https://monitor.hmny.io/status

The number of the next epoch can be calculated based on the current number of blocks and the number of blocks per epoch.

check  internal/configs/sharding/mainnet.go on how to calculate next epoch, the block per epoch is 2^15, and the epoch 0 has 21*2^14 blocks.

**Comment by jhd2best** [comment]
already support `Blocks To Next Epoch` in watchdog

**Comment by jhd2best** [comment]
already support Blocks To Next Epoch in status page
