### ISSUE TITLE
display beacon chain block for non-beacon nodes

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/watchdog#28]
We can query the block number of the beacon chain blocks synced on validators of s1/s2/s3.
```
curl -s --request POST 'http://127.0.0.1:9500/' --header 'Content-Type: application/json' --data-raw '{ "jsonrpc": "2.0", "method": "hmyv2_getLatestChainHeaders", "params": [], "id": 1}' | jq .
```

I'd expect to see the number displayed on watchdog next to the block number of it's own shard.

**Comment by jhd2best** [comment]
already launched on watchdog
