### ISSUE TITLE
stop the alert if the condition is recovered

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/watchdog#30]
In our current watchdog, we trigger an alert if consensus is broken or the node is out of sync.  However, we don't have a way to automatically resolve the pager even if the condition is cleared.  Please add it to auto-resolve the pager.

**Comment by jhd2best** [comment]
already add auto-resolve logic and launch on mainnet. will pay attention for the effect in PagerDuty later

**Comment by jhd2best** [comment]
seems works well
![image](https://user-images.githubusercontent.com/8352895/127748174-7958eb1d-94ab-4fcf-a1e1-98a0781fc53d.png)
