### ISSUE TITLE
monitoring pending crosslink and cross-shard receipt in watchdog

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/watchdog#31]
The RPC is already supported.
https://github.com/harmony-one/harmony/issues/2085

We can monitor them in watchdog at first.  May trigger a pager if the number of pending crosslink and cross-shard receipts is increasing fast.

**Comment by jhd2best** [comment]
check the latest RPC code. can not find `hmy_getNumPendingCrossLinks` method mentioned in issue(https://github.com/harmony-one/harmony/issues/2085). pleash help me check it. thanks. @LeoHChen

**Comment by jhd2best** [comment]
already launch `cross-shard receipts monitor` on watchdog of mainnet. see PR:https://github.com/harmony-one/watchdog/commit/5110869dbc1405874d3e2a6e26d7c5fb17e098ae
