### ISSUE TITLE
change the severity alert for beacon chain out of sync 

### ISSUE THREAD

**Issue by sophoah** [harmony-one/watchdog#46]
Today, all `beacon chain out of sync` alerts have the same severity of `high` for both explorer and validator node.

Shard 1/2/3 explorer node beacon chain out of sync is not a critical issue. It only affects validator node runner wanting to check the S0 last block. Let's update the severity to `low` for `beacon chain out of sync`  alert

**Comment by jhd2best** [comment]
see https://github.com/harmony-one/watchdog/pull/47
