### ISSUE TITLE
crosslink delay alert is missing

### ISSUE THREAD

**Issue by sophoah** [harmony-one/watchdog#50]
No alert of the shard pending crosslink on watchdog
![image](https://user-images.githubusercontent.com/35721420/166499747-90344f29-a71c-4843-acba-874c5cc37ca2.png)
in this picture the shard 2 crosslink is 424 blocks behind (max block - last crosslink)

Let's have an alert when that crosslink is above 500.

**Comment by MaxMustermann2** [comment]
Resolved by #58
