### ISSUE TITLE
consensus shows false on watchdog page but it is actually fine.

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/watchdog#6]
On the dryrun network, shard0 consensus shows false, but the shard0 was doing fine with consensus ongoing. Since watchdog is such an important piece to determine the network state, we should display the right info over there.

![image](https://user-images.githubusercontent.com/4513927/81234469-aa730400-8fad-11ea-867d-84147c32d75a.png)

![image](https://user-images.githubusercontent.com/4513927/81234529-cc6c8680-8fad-11ea-9c8e-11afd944ac92.png)

**Comment by janet-harmony** [comment]
@LeoHChen Did Watchdog say consensus false until you restarted it?
