### ISSUE TITLE
display a short blskey and blskey index

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/watchdog#7]
Please shorten the display of the blskey in watchdog, like first 3 ... and last 3 chars would be enough to identify blskey.  Also, for each blskey, please display their corresponding blskey index.  The index can be found in our code, like harmony.go and tn_harmony.go, those can be configurable in the yaml file.

**Comment by janet-harmony** [comment]
Shortened BLS key display in #9.

**Comment by LeoHChen** [comment]
I would expect to display the index of the key as well, which is much easier to read/check.

**Comment by jhd2best** [comment]
issue for blskey index already exist: https://github.com/harmony-one/watchdog/issues/20
